
import static java.lang.String.valueOf;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER LAPTOP
 */
public class NewJFrame2 extends javax.swing.JFrame {
    public static int tno;
    /**
     * Creates new form NewJFrame2
     */
    public NewJFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        jLabel7 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 3, 36)); // NOI18N
        jLabel1.setText("Ticket Booking");

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel2.setText("From Station");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","Chidambaram(CBM)", "Coimbatore(CBE)", "Chennai(CH)", "Dindigul(DL)", "DharmapuriDMP)", "Delhi", "Madurai(MDU)", "Rameswaram(RSM)", "Sattur(STR)", "Sivakasi(SVKS)", "Virudhunagar(VNR)", "Thirumangalam", "Tirunelveli(TVL)", "Thoothukudi(TN)", "Tenkasi(TK)", "Tanjore(TN)", "KanyaKumari(KN)", "Kovilpatti(KVP)", "Villupuram(VL)", "Srirangam", "Trichy(TRY)", "Karur(KRR)", "Erode(EDE)", "Bangalore(BGE)", "Kancheepuram(KCP)", "Virudhachalam(VCM)", "Tambaram(TBM)", "Chengalpat(CGP)", " ", " ", " ", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel3.setText("To Station");

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel4.setText("DD/MM/YYYY");

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel5.setText("Class");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","SLEEPER(AC)-(Tier -III)", "Tier - II", "SLEEPER(NON AC)", "Tier -I" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel6.setText("No Of Passenger");

        textField1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(0, 0, 255));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.setEnabled(false);
        button1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        button1.setLabel("Next");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(255, 102, 102));
        button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button2.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        button2.setLabel("Save");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setBackground(new java.awt.Color(255, 255, 153));
        button3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button3.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        button3.setLabel("Back");
        button3.setName("Back"); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 255));
        jLabel7.setText("Only 3 Persons");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","Chidambaram(CBM)", "Coimbatore(CBE)", "Chennai(CH)", "Dindigul(DL)", "DharmapuriDMP)", "Delhi", "Madurai(MDU)", "Rameswaram(RSM)", "Sattur(STR)", "Sivakasi(SVKS)", "Virudhunagar(VNR)", "Thirumangalam", "Tirunelveli(TVL)", "Thoothukudi(TN)", "Tenkasi(TK)", "Tanjore(TN)", "KanyaKumari(KN)", "Kovilpatti(KVP)", "Villupuram(VL)", "Srirangam", "Trichy(TRY)", "Karur(KRR)", "Erode(EDE)", "Bangalore(BGE)", "Kancheepuram(KCP)", "Virudhachalam(VCM)", "Tambaram(TBM)", "Chengalpat(CGP)", " ", " ", " ", " "  }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(523, 523, 523)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(166, 166, 166)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(393, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(607, 607, 607)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addComponent(jLabel4))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(181, 181, 181))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        Choice s=new Choice();
        s.setVisible(true);
        NewJFrame2 d=new NewJFrame2();
        this.dispose();
    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
       
        button1.setEnabled(false);
        String FS=jComboBox1.getSelectedItem().toString();
        
        String TS=jComboBox4.getSelectedItem().toString();
        String Cl=jComboBox3.getSelectedItem().toString();
        String d=textField1.getText();
        if(FS.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Select Starting Station:");
        }
        else if(TS.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Select any Destination:");
        }
        else if(Cl.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Select Any Class");
        }
        else if(d.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter the No of Passenger to book Tickets::");
        }
        else 
        {
            int a=jComboBox1.getSelectedIndex();
            int b=jComboBox4.getSelectedIndex();
            
            if(a==0&&b==0)
           {
               JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
               
           }
            else if(a==1&&b==1)
           {
               JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
           }
           else if(a==2&&b==2)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==3&&b==3)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==4&&b==4)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==5&&b==5)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==6&&b==6)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==7&&b==7)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==8&&b==8)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==9&&b==9)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==10&&b==10)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==11&&b==11)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==12&&b==12)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==13&&b==13)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==14&&b==14)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==15&&b==15)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else  if(a==16&&b==16)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==17&&b==17)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==18&&b==19)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==19&&b==19)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==20&&b==20)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==21&&b==21)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==22&&b==22)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==23&&b==23)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
           else if(a==24&&b==24)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
           else if(a==25&&b==25)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
           else if(a==26&&b==26)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
           else if(a==27&&b==27)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
           else if(a==3&&b==9||a==9&&b==3||a==3&&b==7||a==7&&b==3||a==3&&b==11||a==11&&b==3||a==3&&b==12||a==12&&b==3||a==3&&b==13||a==13&&b==3)
            {
                JOptionPane.showMessageDialog(null, "SuccessFully Saved");
                JOptionPane.showMessageDialog(null, "Your Temporary Ticket Number for Booking is"+ ++tno);
                JOptionPane.showMessageDialog(null, "This will be useful for Future Reference");
                
                button1.setEnabled(true);
                 try 
        {
            Class<?> forName = Class.forName("com.mysql.cj.jdbc.Driver");
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        Connection con=null;
       try
       {
            
           con=(Connection) DriverManager.getConnection( "jdbc:mysql://localhost:3306/Train","root","");
       }
       catch (SQLException e)
       {
           System.out.println("OOPS,Error");
           e.printStackTrace();
       }     
        String query = " insert into  bookticket(From_Station,To_Station,Date,Class,No_Of_Passenger,tno)"+ " values (?,?,?,?,?,?)";
        PreparedStatement s=null;
        try
        {
            s = con.prepareStatement(query);
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.setString(1,jComboBox1.getSelectedItem().toString());
        }catch (SQLException ex) 
        {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.setString(2,jComboBox4.getSelectedItem().toString());
        
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.setString(4,jComboBox3.getSelectedItem().toString());
        
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
           s.setString(5,textField1.getText());
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.setString(3,((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText());
        } 
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.setInt(6,tno);
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.execute();
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        try  
        {
            con.close();
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        button1.setEnabled(true);
        
        
                
            }
            else if(a==3&&b==14||a==14&&b==3||a==3&&b==15||a==15&&b==3||a==3&&b==18||a==18&&b==3||a==3&&b==19||a==19&&b==3||a==3&&b==20||a==20&&b==3)
            {
                JOptionPane.showMessageDialog(null, "SuccessFully Saved");
                JOptionPane.showMessageDialog(null, "Your Temporary Ticket Number for Booking is"+ ++tno);
                JOptionPane.showMessageDialog(null, "This will be useful for Future Reference");
                
                button1.setEnabled(true);
                 try 
        {
            Class<?> forName = Class.forName("com.mysql.cj.jdbc.Driver");
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        Connection con=null;
       try
       {
            
           con=(Connection) DriverManager.getConnection( "jdbc:mysql://localhost:3306/Train","root","");
       }
       catch (SQLException e)
       {
           System.out.println("OOPS,Error");
           e.printStackTrace();
       }     
        String query = " insert into  bookticket(From_Station,To_Station,Date,Class,No_Of_Passenger,tno)"+ " values (?,?,?,?,?,?)";
        PreparedStatement s=null;
        try
        {
            s = con.prepareStatement(query);
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.setString(1,jComboBox1.getSelectedItem().toString());
        }catch (SQLException ex) 
        {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.setString(2,jComboBox4.getSelectedItem().toString());
        
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.setString(4,jComboBox3.getSelectedItem().toString());
        
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
           s.setString(5,textField1.getText());
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.setString(3,((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText());
        } 
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.setInt(6,tno);
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.execute();
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        try  
        {
            con.close();
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        button1.setEnabled(true);
        
        
              
            }
            else if(a==3&&b==21||a==21&&b==3||a==3&&b==22||a==22&&b==3||a==3&&b==23||a==23&&b==3||a==3&&b==24||a==24&&b==3||a==3&&b==26||a==26&&b==3||a==3&&b==27||a==27&&b==3||a==3&&b==28||a==28&&b==3){
                JOptionPane.showMessageDialog(null, "SuccessFully Saved");
                JOptionPane.showMessageDialog(null, "Your Temporary Ticket Number for Booking is"+ ++tno);
                JOptionPane.showMessageDialog(null, "This will be useful for Future Reference");
                
                button1.setEnabled(true);
             try 
        {
            Class<?> forName = Class.forName("com.mysql.cj.jdbc.Driver");
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        Connection con=null;
       try
       {
            
           con=(Connection) DriverManager.getConnection( "jdbc:mysql://localhost:3306/Train","root","");
       }
       catch (SQLException e)
       {
           System.out.println("OOPS,Error");
           e.printStackTrace();
       }     
        String query = " insert into  bookticket(From_Station,To_Station,Date,Class,No_Of_Passenger,tno)"+ " values (?,?,?,?,?,?)";
        PreparedStatement s=null;
        try
        {
            s = con.prepareStatement(query);
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.setString(1,jComboBox1.getSelectedItem().toString());
        }catch (SQLException ex) 
        {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
                try {
                    s.setString(2,jComboBox4.getSelectedItem().toString());
                } catch (SQLException ex) {
                    Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
                }
        try
        {
            s.setString(4,jComboBox3.getSelectedItem().toString());
        
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
           s.setString(5,textField1.getText());
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.setString(3,((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText());
        } 
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.setInt(6,tno);
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            s.execute();
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        try  
        {
            con.close();
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
       // button1.setEnabled(true);
        
        }
                
          
                                 
               else
               {
                   JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
                   
               }
       
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        String d=textField1.getText();    
        /*int a=jComboBox1.getSelectedIndex();
            int b=jComboBox2.getSelectedIndex();
           //JOptionPane.showMessageDialog(null,a);
           //JOptionPane.showMessageDialog(null,+b);
            
            if(a==0&&b==0)
           {
               JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
           }
            else if(a==1&&b==1)
           {
               JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
           }
           else if(a==2&&b==2)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==3&&b==3)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==4&&b==4)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==5&&b==5)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==6&&b==6)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==7&&b==7)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==8&&b==8)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==9&&b==9)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==10&&b==10)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==11&&b==11)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==12&&b==12)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==13&&b==13)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==14&&b==14)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==15&&b==15)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else  if(a==16&&b==16)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==17&&b==17)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==18&&b==19)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==19&&b==19)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==20&&b==20)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==21&&b==21)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==22&&b==22)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
            else if(a==23&&b==23)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
           else if(a==24&&b==24)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
           else if(a==25&&b==25)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
           else if(a==26&&b==26)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
           else if(a==27&&b==27)
            {
                JOptionPane.showMessageDialog(null, "No Trains B/W Selected Stations");
            }
           else if(a==2&&b==8||a==8&&b==2||a==2&&b==6||a==6&&b==2||a==2&&b==10||a==10&&b==2||a==2&&b==11||a==11&&b==2||a==2&&b==12||a==12&&b==2)
            {
                
                new Traindet().setVisible(true);
                dispose();
            }
            else if(a==2&&b==13||a==13&&b==2||a==2&&b==14||a==14&&b==2||a==2&&b==17||a==17&&b==2||a==2&&b==18||a==18&&b==2||a==2&&b==19||a==19&&b==2)
            {
              new Traindet().setVisible(true);
                dispose();
            }
            else if(a==2&&b==20||a==20&&b==2||a==2&&b==21||a==21&&b==2||a==2&&b==22||a==22&&b==2||a==2&&b==23||a==23&&b==2||a==2&&b==25||a==25&&b==2||a==2&&b==26||a==26&&b==2||a==2&&b==27||a==27&&b==2){new Traindet().setVisible(true);
                dispose();}
          
          
                                 
               else
               {
                   String d=textField1.getText();
               }*/
        
            new person().setVisible(true);
            dispose();
            
            
            
                    
                    
            
            
            
            
            
            
               
        
            
        
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
