
import java.util.Random;
import javax.swing.JOptionPane;





/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER LAPTOP
 */
public class Traindet extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public static int b = 100;
    public static int c = 100;
    public static int d = 100;
    public static int e = 100;
    public static int f = 100;
    public static int g = 100;
    public Traindet() {
        
        initComponents();
        show.setText(String.valueOf(b));
        jTextField2.setText(String.valueOf(c));
        jTextField6.setText(String.valueOf(d));
        jTextField7.setText(String.valueOf(e));
        jTextField8.setText(String.valueOf(f));
        jTextField5.setText(String.valueOf(g));
        
        
    }
    /*public void data()
    {
        try
        {
         Class.forName("com.mysql.jdbc.Driver");
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Train","root","");
         Statement stmt = con.createStatement();
         String q="Select * from ticket  ";
         PreparedStatement pst=con.prepareStatement(q);
         ResultSet rs=pst.executeQuery();
         while(rs.next())
         {
             String count,name;
             count=rs.getString("count");
             name=rs.getString("name");
             if(name.equals("PandyanExpress"))
             {
                 c=Integer.parseInt(count);
             }
         }
        }
        catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null, ex);
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        show = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1541, 947));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("The Available Trains are");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Pandyan Express");

        jButton1.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton2.setText("Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton3.setText("Book");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton5.setText("Book");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Pearl City Express ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Vaigai Express");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("NELLAI Express");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Pothigai Express");

        jButton6.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton6.setText("Book");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t5.jpg"))); // NOI18N
        jLabel8.setText("jLabel2");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t2.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t6 (3).jpg"))); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t3.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");

        jButton7.setBackground(new java.awt.Color(255, 255, 153));
        jButton7.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton8.setText("Book");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t7.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("MYSORE EXPRESS");

        show.setBackground(new java.awt.Color(255, 204, 0));
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(255, 204, 51));

        jTextField5.setBackground(new java.awt.Color(255, 204, 0));

        jTextField6.setBackground(new java.awt.Color(255, 204, 0));

        jTextField7.setBackground(new java.awt.Color(255, 204, 0));

        jTextField8.setBackground(new java.awt.Color(255, 204, 0));

        jLabel14.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 255));
        jLabel14.setText("AVAILABLE TICKETS:");

        jLabel15.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel15.setText("Re-Enter No-Of Passengers to Confirm");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(57, 57, 57))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(295, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel15)
                .addGap(41, 41, 41)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel14))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel10)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 247, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1483, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       String a=jTextField1.getText();
       if(a.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Enter the Number Of Passengers:");
       }
       else
       {
      
        int temp1=Integer.parseInt(jTextField1.getText());
        
        b=b-temp1;
        if(b==-1)
        {
            JOptionPane.showMessageDialog(null, "Ticket Not Available:,SORRY");
        }
        else
        {
        String b1 = String.valueOf(b);
        show.setText(b1);
        JOptionPane.showMessageDialog(null, "You Selected Pandyan Express");
       JOptionPane.showMessageDialog(null, "TICKET IS SELECTED SUCESSFULLY..");
       int tmnt=Integer.parseInt(a);
        int w=tmnt*390+25;
             JOptionPane.showMessageDialog(null, "You have to Pay the amount of: "+w);
       
       String s="";
        for(int i=0;i<temp1;i++)
        {
            s=s+seatNot()+",";
        }
        int q=seatNot();
        if(q<=25)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"L"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 8.00PM");
        }
        else if(q>25||q<=50)
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"U"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 8.00PM");
        }
        else if(q>50||q<=75)
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"M"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 8.00PM");
        }
        else
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"S"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 8.00PM");
        }
        
        JOptionPane.showMessageDialog(null, "You have to pay amount now:");
        new PAyment().setVisible(true);
        dispose();
       }    
       }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      /* String a=jTextField1.getText();
       if(a.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Enter the Number Of Passengers:");
       }
       else
       {
        int temp1=Integer.parseInt(jTextField1.getText());
        
        c=c-temp1;
        
        if(c==0)
        {
            JOptionPane.showMessageDialog(null, "Ticket Not Available:,SORRY");
        }
        else
        {
        String b1 = String.valueOf(c);
        jTextField5.setText(b1);
        JOptionPane.showMessageDialog(null, "You Selected PearlCity Express");
       JOptionPane.showMessageDialog(null, "TICKET IS SELECTED SUCESSFULLY..");
       int tmnt=Integer.parseInt(a);
        int w=tmnt*360+25;
             JOptionPane.showMessageDialog(null, "You have to Pay the amount of: "+w);
       String s="";
        for(int i=0;i<temp1;i++)
        {
            s=s+seatNot()+",";
        }
        int q=seatNot();
        if(q<=25)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"L"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.00PM");
        }
        else if(q>25 ||q<=50)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"M"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.00PM");
        }
        
        else if(q>50 || q<=75)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"U"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.00PM");
        }
        else
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"S"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.00PM");
        }
        
        
        JOptionPane.showMessageDialog(null, "You have to pay amount now:");
        new PAyment().setVisible(true);
        dispose();
       }    
       }*/
            String a=jTextField1.getText();
       if(a.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Enter the Number Of Passengers:");
       }
       else
       {
      
        int temp1=Integer.parseInt(jTextField1.getText());
        
        g=g-temp1;
        if(g==-1)
        {
            JOptionPane.showMessageDialog(null, "Ticket Not Available:,SORRY");
        }
        else
        {
        String b1 = String.valueOf(g);
        jTextField5.setText(b1);
        JOptionPane.showMessageDialog(null, "You Selected PearlCity Express");
       JOptionPane.showMessageDialog(null, "TICKET IS SELECTED SUCESSFULLY..");
       int tmnt=Integer.parseInt(a);
        int w=tmnt*385+25;
             JOptionPane.showMessageDialog(null, "You have to Pay the amount of: "+w);
       
       String s="";
        for(int i=0;i<temp1;i++)
        {
            s=s+seatNotaa()+",";
        }
        int q=seatNotaa();
        if(q<=25)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"L"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.00PM");
        }
        else if(q>25||q<=50)
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"U"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.00PM");
        }
        else if(q>50||q<=75)
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"M"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.00PM");
        }
        else
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"S"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.00PM");
        }
        
        JOptionPane.showMessageDialog(null, "You have to pay amount now:");
        new PAyment().setVisible(true);
        dispose();
       }    
       }
                                          
 
    }//GEN-LAST:event_jButton2ActionPerformed
    
        
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       /* String a=jTextField1.getText();
        if(a.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Enter the Number Of Passengers:");
       }
       else
       {
        int temp1=Integer.parseInt(jTextField1.getText());
        d=d-temp1;
        if(d==0)
        {
            JOptionPane.showMessageDialog(null, "Ticket Not Available:,SORRY");
        }
        else
        {
        String b1 = String.valueOf(d);
        jTextField8.setText(b1);
        JOptionPane.showMessageDialog(null, "You Selected Nellai Express");
       JOptionPane.showMessageDialog(null, "TICKET IS SELECTED SUCESSFULLY..");
       int tmnt=Integer.parseInt(a);
        int w=tmnt*250+25;
             JOptionPane.showMessageDialog(null, "You have to Pay the amount of: "+w);
       String s="";
        for(int i=0;i<temp1;i++)
        {
            s=s+seatN()+",";
        }
        int q=seatN();
        if(q<=25)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"L"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.30PM");
        }
        else if(q<=50||q>25)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"U"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.30PM");
        }
        else if(q<=75||q>50)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"M"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.30PM");
        }
        else
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"S"+s);
        }
        //JOptionPane.showMessageDialog(null, "You Selected Mysuru Express");
        JOptionPane.showMessageDialog(null, "You have to pay amount now:");
        new PAyment().setVisible(true);
        dispose();  
    }//GEN-LAST:event_jButton3ActionPerformed
    }}*/
       String a=jTextField1.getText();
       if(a.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Enter the Number Of Passengers:");
       }
       else
       {
      
        int temp1=Integer.parseInt(jTextField1.getText());
        
        f=f-temp1;
        if(f==-1)
        {
            JOptionPane.showMessageDialog(null, "Ticket Not Available:,SORRY");
        }
        else
        {
        String b1 = String.valueOf(f);
        jTextField8.setText(b1);
        JOptionPane.showMessageDialog(null, "You Selected Nellai Express");
       JOptionPane.showMessageDialog(null, "TICKET IS SELECTED SUCESSFULLY..");
       int tmnt=Integer.parseInt(a);
        int w=tmnt*340+25;
             JOptionPane.showMessageDialog(null, "You have to Pay the amount of: "+w);
       
       String s="";
        for(int i=0;i<temp1;i++)
        {
            s=s+seatNotal()+",";
        }
        int q=seatNotal();
        if(q<=25)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"L"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.30PM");
        }
        else if(q>25||q<=50)
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"U"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.30PM");
        }
        else if(q>50||q<=75)
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"M"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.30PM");
        }
        else
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"S"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 7.30PM");
        }
        
        JOptionPane.showMessageDialog(null, "You have to pay amount now:");
        new PAyment().setVisible(true);
        dispose();
       }    
       }}
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You Selected Vaigai Express");
        JOptionPane.showMessageDialog(null, "You have to pay amount now:");
        new PAyment().setVisible(true);
        dispose(); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       /* String a=jTextField1.getText();
        if(a.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Enter the Number Of Passengers:");
       }
       else
       {
        int temp1=Integer.parseInt(jTextField1.getText());
        e=e-temp1;
        if(e==0)
        {
            JOptionPane.showMessageDialog(null, "Ticket Not Available:,SORRY");
        }
        else{
        String b1 = String.valueOf(e);
        jTextField7.setText(b1);
        JOptionPane.showMessageDialog(null, "You Selected Mysuru Express");
       JOptionPane.showMessageDialog(null, "TICKET IS SELECTED SUCESSFULLY..");
       int tmnt=Integer.parseInt(a);
        int w=tmnt*420+25;
             JOptionPane.showMessageDialog(null, "You have to Pay the amount of: "+w);
       
       String s="";
        for(int i=0;i<temp1;i++)
        {
            s=s+seatNota()+",";
        }
        int q=seatNota();
        if(q<=25)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"L"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 5.00PM ");
        }
        else if(q<=50||q>25)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"M"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 5.00PM ");
        }
        else if(q>50||q<=75)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"U"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 5.00PM ");
        }
        else
        {
           
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"S"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 5.00PM ");
        }
        
        //JOptionPane.showMessageDialog(null, "You Selected Nellai Express");
        JOptionPane.showMessageDialog(null, "You have to pay amount now:");
        new PAyment().setVisible(true);
        dispose(); 
    }//GEN-LAST:event_jButton5ActionPerformed
    }}*/
    String a=jTextField1.getText();
       if(a.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Enter the Number Of Passengers:");
       }
       else
       {
      
        int temp1=Integer.parseInt(jTextField1.getText());
        
        e=e-temp1;
        if(e==-1)
        {
            JOptionPane.showMessageDialog(null, "Ticket Not Available:,SORRY");
        }
        else
        {
        String b1 = String.valueOf(e);
        jTextField7.setText(b1);
        JOptionPane.showMessageDialog(null, "You Selected Mysuru Express");
       JOptionPane.showMessageDialog(null, "TICKET IS SELECTED SUCESSFULLY..");
       int tmnt=Integer.parseInt(a);
        int w=tmnt*400+25;
             JOptionPane.showMessageDialog(null, "You have to Pay the amount of: "+w);
       
       String s="";
        for(int i=0;i<temp1;i++)
        {
            s=s+seatNota()+",";
        }
        int q=seatNota();
        if(q<=25)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"L"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 5.00PM");
        }
        else if(q>25||q<=50)
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"U"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 5.00PM");
        }
        else if(q>50||q<=75)
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"M"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 5.00PM");
        }
        else
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"S"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 5.00PM");
        }
        
        JOptionPane.showMessageDialog(null, "You have to pay amount now:");
        new PAyment().setVisible(true);
        dispose();
       }    
       }
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      /* String a=jTextField1.getText();
       if(a.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Enter the Number Of Passengers:");
       }
       else
       {
           int temp1=Integer.parseInt(jTextField1.getText());
       
        f=f-temp1;
        if(f==0)
        {
            JOptionPane.showMessageDialog(null, "Ticket Not Available:,SORRY");
        }
        else {
        String b1 = String.valueOf(f);
        jTextField2.setText(b1);
        JOptionPane.showMessageDialog(null, "You Selected Vaigai Express");
       JOptionPane.showMessageDialog(null, "TICKET IS SELECTED SUCESSFULLY..");
       int tmnt=Integer.parseInt(a);
        int w=tmnt*220+25;
             JOptionPane.showMessageDialog(null, "You have to Pay the amount of: "+w);
       String s="";
        for(int i=0;i<temp1;i++)
        {
            s=s+seatNotal()+",";
        }
        
        int q=seatNotal();
        //JOptionPane.showMessageDialog(null, q);
        if(q<=25)
        {
           // JOptionPane.showMessageDialog(null,"L");
           JOptionPane.showMessageDialog(null, """
                                                YOUR SEAT NUMBERS ARE : L
                                               """+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 8.30PM");
        }
        else if(q>25 || q<=50)
        {
            //JOptionPane.showMessageDialog(null,"U");
           JOptionPane.showMessageDialog(null, """
                                                YOUR SEAT NUMBERS ARE : U
                                               """+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 8.30PM"); 
        }
        else if(q>50 || q<=75)
        {
            //JOptionPane.showMessageDialog(null,"M");
           JOptionPane.showMessageDialog(null, """
                                                YOUR SEAT NUMBERS ARE : M
                                               """+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 8.30PM"); 
        }
        else 
        {
           JOptionPane.showMessageDialog(null, """
                                                YOUR SEAT NUMBERS ARE :
                                               S"""+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 8.30PM"); 
        }
        //JOptionPane.showMessageDialog(null, "You Selected Vaigai Express");
        JOptionPane.showMessageDialog(null, "You have to pay amount now:");
        new PAyment().setVisible(true);
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
    }}*/
      String a=jTextField1.getText();
       if(a.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Enter the Number Of Passengers:");
       }
       else
       {
      
        int temp1=Integer.parseInt(jTextField1.getText());
        
        c=c-temp1;
        if(c==-1)
        {
            JOptionPane.showMessageDialog(null, "Ticket Not Available:,SORRY");
        }
        else
        {
        String b1 = String.valueOf(c);
        jTextField2.setText(b1);
        JOptionPane.showMessageDialog(null, "You Selected Vaigai Express");
       JOptionPane.showMessageDialog(null, "TICKET IS SELECTED SUCESSFULLY..");
       int tmnt=Integer.parseInt(a);
        int w=tmnt*395+25;
             JOptionPane.showMessageDialog(null, "You have to Pay the amount of: "+w);
       
       String s="";
        for(int i=0;i<temp1;i++)
        {
            s=s+seatNo()+",";
        }
        int q=seatNo();
        if(q<=25)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"L"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 6.00PM");
        }
        else if(q>25||q<=50)
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"U"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 6.00PM");
        }
        else if(q>50||q<=75)
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"M"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 6.00PM");
        }
        else
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"S"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 6.00PM");
        }
        
        JOptionPane.showMessageDialog(null, "You have to pay amount now:");
        new PAyment().setVisible(true);
        dispose();
       }    
       }
    }
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       /* String a=jTextField1.getText();
        if(a.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Enter the Number Of Passengers:");
       }
       else
       {
        int temp1=Integer.parseInt(jTextField1.getText());
        g=g-temp1;
        if(g==0)
        {
            JOptionPane.showMessageDialog(null, "Ticket Not Available:,SORRY");
        }
        else
        {
        String b1 = String.valueOf(g);
        jTextField6.setText(b1);
        JOptionPane.showMessageDialog(null, "You Selected Pothigai Express");
       JOptionPane.showMessageDialog(null, "TICKET IS SELECTED SUCESSFULLY..");
       String s="";
        for(int i=0;i<temp1;i++)
        {
            s=s+seatNotaa()+",";
        }
        int q=seatNotaa();
        if(q<=25)
        {
        
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"L"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 6.30PM");
        }
        else if(q>25 ||q<=50)
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"M"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 6.30PM");
        }
        else if(q>50 ||q<=75)
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"U"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 6.30PM");
        }
        else
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"S"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 6.30PM");
        }
        
         //JOptionPane.showMessageDialog(null, "You Selected Pothigai Express");
        JOptionPane.showMessageDialog(null, "You have to pay amount now:");
        new PAyment().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed
    }}*/
       String a=jTextField1.getText();
       if(a.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Enter the Number Of Passengers:");
       }
       else
       {
      
        int temp1=Integer.parseInt(jTextField1.getText());
        
        d=d-temp1;
        if(d==-1)
        {
            JOptionPane.showMessageDialog(null, "Ticket Not Available:,SORRY");
        }
        else
        {
        String b1 = String.valueOf(g);
        jTextField6.setText(b1);
        JOptionPane.showMessageDialog(null, "You Selected Pothigai Express");
       JOptionPane.showMessageDialog(null, "TICKET IS SELECTED SUCESSFULLY..");
       int tmnt=Integer.parseInt(a);
        int w=tmnt*400+25;
             JOptionPane.showMessageDialog(null, "You have to Pay the amount of: "+w);
       
       String s="";
        for(int i=0;i<temp1;i++)
        {
            s=s+seatN()+",";
        }
        int q=seatN();
        if(q<=25)
        {
           JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"L"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 6.30PM");
        }
        else if(q>25||q<=50)
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"U"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 6.30PM");
        }
        else if(q>50||q<=75)
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"M"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 6.30PM");
        }
        else
        {
            JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+"S"+s);
           //JOptionPane.showMessageDialog(null, " YOUR SEAT NUMBERS ARE :\n"+s);
           JOptionPane.showMessageDialog(null, " THE TRAIN IS SCHEDULED AT 6.30PM");
        }
        
        JOptionPane.showMessageDialog(null, "You have to pay amount now:");
        new PAyment().setVisible(true);
        dispose();
       }    
       }
    }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            new NewJFrame2().setVisible(true);
            dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
                    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Traindet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Traindet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Traindet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Traindet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Traindet().setVisible(true);
            }
        });

    }
public int seatNot()
    {
        Random random = new Random();
        int b= random.nextInt(99);
        return Integer.valueOf(b);
    }
public int seatNo()
    {
        Random random = new Random();
        int c= random.nextInt(99);
        return Integer.valueOf(c);
    }
public int seatN()
    {
        Random random = new Random();
        int d= random.nextInt(99);
        return Integer.valueOf(d);
    }
public int seatNota()
    {
        Random random = new Random();
        int e= random.nextInt(99);
        return Integer.valueOf(e);
    }
public int seatNotal()
    {
        Random random = new Random();
        int f= random.nextInt(99);
        return Integer.valueOf(f);
    }
public int seatNotaa()
    {
        Random random = new Random();
        int g= random.nextInt(99);
        return Integer.valueOf(g);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField show;
    // End of variables declaration//GEN-END:variables
    
}
